# Generated by Django 4.1.1 on 2022-10-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('FuelType', models.CharField(max_length=25)),
                ('Colour', models.CharField(max_length=25)),
                ('LicencePlate', models.CharField(max_length=12)),
                ('Status', models.BooleanField(default=False)),
                ('Mileage', models.PositiveIntegerField()),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='car',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype'),
        ),
    ]
