# Generated by Django 4.1.1 on 2022-10-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_car_cartype_delete_student_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Type',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
