# Generated by Django 4.1.1 on 2022-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_car_branch_remove_car_type_delete_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('DailyCost', models.FloatField()),
                ('WeeklyCost', models.FloatField()),
                ('MonthlyCost', models.FloatField()),
                ('LateFee', models.FloatField()),
                ('DiffBranchFee', models.FloatField()),
            ],
        ),
    ]
