# Generated by Django 4.1.1 on 2022-10-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
        migrations.AddField(
            model_name='car',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BranchID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
