# Generated by Django 4.1.1 on 2022-10-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_car_branch_car_type_alter_branch_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BranchID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='Branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.cartype'),
        ),
    ]
