# Generated by Django 4.1.1 on 2022-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_branch_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BranchID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
