# Generated by Django 4.1.1 on 2022-10-09 23:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_car_branch_alter_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='City',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='branch',
            name='PostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='branch',
            name='Province',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='branch',
            name='StreetName',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='StreetNumber',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='branch',
            name='UnitNumber',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
