# Generated by Django 4.1.1 on 2022-10-09 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_employee_branch_city_branch_postalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='City',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='employee',
            name='PostalCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='Province',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='Rank',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='employee',
            name='StreetName',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='StreetNumber',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='employee',
            name='UnitNumber',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
