# Generated by Django 4.1.1 on 2022-10-10 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='WorksAt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('RentalID', models.AutoField(primary_key=True, serialize=False)),
                ('DateFrom', models.DateField()),
                ('DateTo', models.DateField()),
                ('DateReturned', models.DateField()),
                ('TotalCost', models.FloatField()),
                ('LicensePlate', models.CharField(max_length=8)),
                ('GoldMember', models.BooleanField()),
                ('BranchFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComesFrom', to='api.branch')),
                ('BranchTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GoesTo', to='api.branch')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('CarType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartype')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.employee')),
            ],
        ),
    ]
