# Generated by Django 4.1.1 on 2022-10-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employee_worksat_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UnitNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='UnitNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
