# Generated by Django 4.1.3 on 2022-11-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_rental_datereturned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='LicencePlate',
            new_name='LicensePlate',
        ),
    ]
