# Generated by Django 4.1.3 on 2022-11-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_rental_employee_alter_rental_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Banned',
            field=models.BooleanField(default=False),
        ),
    ]
